"""Build the conceptual motivation and an explicitly empty diagnostic panel.

Run from the paper directory: python3 figures/draw_motivation.py
The small prediction bars are schematic, never measured probabilities.
No experimental values or expected curves are generated by this script.
"""

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch


OUT = Path(__file__).resolve().parent
NAVY = "#142D4E"
MUTED = "#596B7C"
BLUE = "#326BC5"
TEAL = "#087E8B"
ORANGE = "#CE7340"
LINE = "#D5DEE7"


def main() -> None:
    plt.rcParams.update({
        "font.family": "DejaVu Sans",
        "mathtext.fontset": "stix",
        "font.size": 18,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "svg.fonttype": "none",
    })
    fig = plt.figure(figsize=(16, 4.6), facecolor="white")
    canvas = fig.add_axes([0, 0, 1, 1])
    canvas.set(xlim=(0, 16), ylim=(0, 4.6))
    canvas.axis("off")

    def text(x, y, value, size=18, color=NAVY, **kwargs):
        return canvas.text(x, y, value, fontsize=size, color=color,
                           va="center", **kwargs)

    text(0.12, 4.29, "(a) Sensitivity vs. correction need", 21, weight="bold")
    text(7.22, 4.29, "(b) Do the directions capture current corrections?", 20,
         weight="bold")
    canvas.plot([6.82, 6.82], [0.2, 4.5], color=LINE, lw=1)

    def prediction_pair(y, matched):
        for i, height in enumerate([0.60, 0.29, 0.11]):
            canvas.bar(0.50 + i * 0.43, height, width=0.15,
                       bottom=y, color=BLUE)
        student = [0.60, 0.29, 0.11] if matched else [0.18, 0.32, 0.50]
        for i, height in enumerate(student):
            canvas.bar(0.68 + i * 0.43, height, width=0.15,
                       bottom=y, color=TEAL)
        canvas.plot([0.34, 1.72], [y, y], color=LINE, lw=1)

    for y in [2.12, 0.48]:
        canvas.add_patch(FancyBboxPatch(
            (0.12, y), 6.37, 1.42, boxstyle="round,pad=0.02,rounding_size=0.10",
            ec=LINE, fc="#F7F9FC", lw=1,
        ))
    text(0.34, 3.28, r"Predictions match: $p_t=q$", 19, weight="bold")
    prediction_pair(2.30, True)
    text(1.98, 2.89, "Fisher can remain nonzero", 17, BLUE)
    text(1.98, 2.41, r"No correction: $u=0,\ G=0$", 19, TEAL)

    text(0.34, 1.64, r"Prediction gap: $p_t\ne q$", 19, weight="bold")
    prediction_pair(0.66, False)
    text(1.98, 1.18, r"$p_t-q\ \longrightarrow\ u=-\nabla_h\mathrm{KL}/d$", 20, TEAL)
    text(1.98, 0.76, r"Output weighting: $G=\mathbb{E}[uu^\top]$", 18)
    text(0.25, 0.16, r"Schematic only", 15, MUTED)
    text(3.20, 0.16, r"$p_t$: expert", 16, BLUE)
    text(4.87, 0.16, r"$q$: current", 16, TEAL)

    axes = fig.add_axes([0.535, 0.25, 0.425, 0.56])
    axes.set(xlim=(3, 22), ylim=(0, 100))
    axes.set_xticks([5, 10, 20], ["5%", "10%", "20%"])
    axes.set_yticks([0, 50, 100])
    axes.set_xlabel("Retained dimension ratio", fontsize=17, labelpad=5)
    axes.set_ylabel("Captured KL energy (%)", fontsize=16, labelpad=8)
    axes.tick_params(labelsize=16, colors=MUTED)
    axes.spines[["top", "right"]].set_visible(False)
    for side in ["left", "bottom"]:
        axes.spines[side].set_color(LINE)
    axes.grid(axis="y", color=LINE, alpha=0.55, linewidth=0.7)
    axes.text(0.5, 0.57, "EXPERIMENT PENDING", transform=axes.transAxes,
              ha="center", va="center", fontsize=22, weight="bold", color=ORANGE)
    axes.text(0.5, 0.33, "Independent samples required; no measured curves",
              transform=axes.transAxes, ha="center", fontsize=15, color=MUTED)
    text(7.30, 0.25, "Planned:", 15, MUTED)
    text(8.52, 0.25, "Current Fisher", 15, BLUE)
    text(10.76, 0.25, "Initial correction", 15, MUTED)
    text(13.29, 0.25, "Current correction", 15, TEAL)

    for extension in ["pdf", "svg"]:
        fig.savefig(OUT / f"ink_motivation.{extension}", facecolor="white")
    plt.close(fig)


if __name__ == "__main__":
    main()
